config/routes.rb
Rails.application.routes.draw do
  root 'post#list'
  get 'post/new' => 'submissions#new', as: :new_post

  get 'post/comment'

  post 'post' => 'post#create', as: :post
  post 'post/:id/score' => 'post#score', as: :score_post

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true
  validates :domain, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def list
    @submissions = Submission.all.order("score DESC")
  end

  def score
    @submission = Submission.find params[:id]
    @submission.update score:(@submission.score.to_i + 1)
    redirect_to root_path
  end


  def comment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditz</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="page-header">
      <h1>Bootleg Reddit <small>The Last Page of the Internet</small></h1>
    </div>
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="#">Hot</a></li>
      <li role="presentation"><a href="#">New</a></li>
      <li role="presentation"><a href="#">Rising</a></li>
      <li role="presentation"><a href="#">Compose New Submission</a></li>
    </ul>


  <%= yield %>
  </div>
</body>
</html>

app/views/post/comment.html.erb
<h1>Post#comment</h1>
<p>Find me in app/views/post/comment.html.erb</p>

app/views/post/list.html.erb
<h1>Very success</h1>

<% @submissions.each do |submission| %>
    <div class="media">
      <div class="media-left media-middle">
        <div class="vote">
          <%= link_to score_post_path(id: submission.id), method: :post do %>
            <i class="glyphicon glyphicon-arrow-up arrow arrow-up"></i>
            <%= submission.score %>
          <% end %>
          <span class="glyphicon glyphicon-arrow-down arrow arrow-down" aria-hidden="true"></span>
        </div>
      </div>
      <div class="media-left media-middle image">
        <a href="#">
          <img class="media-object" src"http://google.com" alt=img src="https://atbrand.com/wp-content/uploads/2015/09/new-google-g-icon.png">
        </a>
      </div>
      <div class="media-body">
        <h3 class="media-heading"><%= link_to submission.title, "http://#{submission.url}" %><small><%= submission.domain %></small></h3>
        submitted <%= distance_of_time_in_words_to_now submission.created_at %> ago by <%= submission.username %>.
      </div>
    </div>
<% end %>

app/views/post/new.html.erb
<div class="container">
  <h2>New Submission</h2>
</div>